version: "2"

services:
  web:
    image: nginx:latest
    container_name: "gateway"
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    image: "gateway/php"
    container_name: "gateway-backend"
    volumes:
      - ../:/var/www
